local util = require("tzfn.util")

return function(palette, styles)
	return {
		ColorColumn = { bg = palette.surface },
		Conceal = { bg = "NONE" },
		CurSearch = { fg = palette.bg, bg = palette.ylw },
		Cursor = { fg = palette.fg, bg = palette.hl3 },
		CursorColumn = { bg = palette.overlay },
		-- CursorIM = {},
		CursorLine = { bg = palette.overlay },
		CursorLineNr = { fg = palette.fg, bold = styles.bold },
		-- DarkenedPanel = { },
		-- DarkenedStatusline = {},
		DiffAdd = { bg = palette.grn, blend = 20 },
		DiffChange = { bg = palette.ylw, blend = 20 },
		DiffDelete = { bg = palette.red, blend = 20 },
		DiffText = { bg = palette.mgt, blend = 40 },
		diffAdded = { link = "DiffAdd" },
		diffChanged = { link = "DiffChange" },
		diffRemoved = { link = "DiffDelete" },
		Directory = { fg = palette.blu2, bold = styles.bold },
		-- EndOfBuffer = {},
		ErrorMsg = { fg = palette.err, bold = styles.bold },
		FloatBorder = { fg = palette.cyn, bg = palette.surface },
		FloatTitle = { fg = palette.cyn, bg = palette.surface, bold = styles.bold },
		FoldColumn = { fg = palette.muted },
		Folded = { fg = palette.fg, bg = palette.surface },
		IncSearch = { link = "CurSearch" },
		LineNr = { fg = palette.muted },
		MatchParen = { fg = palette.grn, bg = palette.grn, blend = 25 },
		ModeMsg = { fg = palette.subtle },
		MoreMsg = { fg = palette.blu2 },
		NonText = { fg = palette.muted },
		Normal = { fg = palette.fg, bg = palette.bg },
		NormalFloat = { bg = palette.surface },
		NormalNC = { fg = palette.fg, bg = styles.dim_inactive and palette._nc or palette.bg },
		NvimInternalError = { link = "ErrorMsg" },
		Pmenu = { fg = palette.subtle, bg = palette.surface },
		PmenuExtra = { fg = palette.muted, bg = palette.surface },
		PmenuExtraSel = { fg = palette.subtle, bg = palette.overlay },
		PmenuMatch = { fg = palette.fg },
		PmenuKind = { fg = palette.blu, bg = palette.surface },
		PmenuKindSel = { fg = palette.subtle, bg = palette.overlay },
		PmenuSbar = { bg = palette.surface },
		PmenuSel = { fg = "NONE", bg = palette.overlay },
		PmenuThumb = { bg = palette.muted },
		Question = { fg = palette.ylw },
		QuickFixLine = { fg = palette.blu },
		-- RedrawDebugNormal = {},
		RedrawDebugClear = { fg = palette.bg, bg = palette.ylw },
		RedrawDebugComposed = { fg = palette.bg, bg = palette.grn },
		RedrawDebugRecompose = { fg = palette.bg, bg = palette.red },
		Search = { fg = palette.fg, bg = palette.ylw, blend = 20 },
		SignColumn = { fg = palette.fg, bg = "NONE" },
		SpecialKey = { fg = palette.blu },
		SpellBad = { sp = palette.subtle, undercurl = true },
		SpellCap = { sp = palette.subtle, undercurl = true },
		SpellLocal = { sp = palette.subtle, undercurl = true },
		SpellRare = { sp = palette.subtle, undercurl = true },
		StatusLine = { fg = palette.subtle, bg = palette.surface, blend = 60 },
		StatusLineNC = { fg = palette.muted, bg = palette.surface, blend = 60 },
		StatusLineTerm = { fg = palette.bg, bg = palette.grn },
		StatusLineTermNC = { fg = palette.bg, bg = palette.grn, blend = 60 },
		Substitute = { link = "IncSearch" },
		TabLine = { fg = palette.subtle, bg = palette.surface },
		TabLineFill = { bg = palette.surface },
		TabLineSel = { fg = palette.fg, bg = palette.overlay, bold = styles.bold },
		Title = { fg = palette.cyn, bold = true },
		VertSplit = { fg = palette.cyn },
		Visual = { bg = palette.blu, blend = 15 },
		-- VisualNOS = {},
		WarningMsg = { fg = palette.ylw, bold = styles.bold },
		-- Whitespace = {},
		WildMenu = { link = "IncSearch" },
		WinBar = { fg = palette.subtle, bg = palette.surface, blend = 60 },
		WinBarNC = { fg = palette.muted, bg = palette.surface, blend = 60 },
		WinSeparator = { fg = palette.cyn },

		DiagnosticError = { fg = palette.err, undercurl = true },
		DiagnosticHint = { fg = palette.cyn },
		DiagnosticInfo = { fg = palette.blu },
		DiagnosticOk = { fg = palette.grn },
		DiagnosticWarn = { fg = palette.ylw },
		DiagnosticDefaultError = { link = "DiagnosticError" },
		DiagnosticDefaultHint = { link = "DiagnosticHint" },
		DiagnosticDefaultInfo = { link = "DiagnosticInfo" },
		DiagnosticDefaultOk = { link = "DiagnosticOk" },
		DiagnosticDefaultWarn = { link = "DiagnosticWarn" },
		DiagnosticFloatingError = { link = "DiagnosticError" },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticFloatingOk = { link = "DiagnosticOk" },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticSignError = { link = "DiagnosticError" },
		DiagnosticSignHint = { link = "DiagnosticHint" },
		DiagnosticSignInfo = { link = "DiagnosticInfo" },
		DiagnosticSignOk = { link = "DiagnosticOk" },
		DiagnosticSignWarn = { link = "DiagnosticWarn" },
		DiagnosticUnderlineError = { sp = palette.err, undercurl = true },
		DiagnosticUnderlineHint = { sp = palette.cyn, undercurl = true },
		DiagnosticUnderlineInfo = { sp = palette.blu, undercurl = true },
		DiagnosticUnderlineOk = { sp = palette.grn, undercurl = true },
		DiagnosticUnderlineWarn = { sp = palette.ylw, undercurl = true },
		DiagnosticVirtualTextError = { fg = palette.err, bg = palette.err, blend = 10 },
		DiagnosticVirtualTextHint = { fg = palette.cyn, bg = palette.cyn, blend = 10 },
		DiagnosticVirtualTextInfo = { fg = palette.blu, bg = palette.blu, blend = 10 },
		DiagnosticVirtualTextOk = { fg = palette.grn, bg = palette.grn, blend = 10 },
		DiagnosticVirtualTextWarn = { fg = palette.ylw, bg = palette.ylw, blend = 10 },

		Boolean = { fg = util.blend(palette.mgt2, palette.mgt, 0.3) },
		Character = { fg = util.blend(palette.grn2, palette.grn, 0.45) },
		Comment = { fg = palette.muted, italic = styles.italic },
		Conditional = { fg = palette.blu },
		Constant = { fg = util.blend(palette.red2, palette.red, 0.3) },
		Debug = { fg = palette.ylw },
		Define = { fg = palette.mgt2 },
		Delimiter = { fg = util.blend(palette.subtle, palette.blu2, 0.7) },
		Error = { fg = palette.err },
		Exception = { fg = palette.blu },
		Float = { fg = util.blend(palette.ylw2, palette.ylw, 0.2) },
		Function = { fg = palette.cyn },
		Identifier = { fg = palette.fg },
		Include = { fg = palette.mgt2 },
		Keyword = { fg = palette.blu, italic = styles.italic },
		Label = { fg = palette.blu2 },
		LspCodeLens = { fg = palette.subtle },
		LspCodeLensSeparator = { fg = palette.muted },
		LspInlayHint = { fg = palette.muted, bg = palette.muted, blend = 10 },
		LspReferenceRead = { bg = util.blend(palette.hl2, palette.overlay, 0.3) },
		LspReferenceText = { bg = util.blend(palette.hl2, palette.overlay, 0.3) },
		LspReferenceWrite = { bg = util.blend(palette.hl2, palette.overlay, 0.3) },
		Macro = { fg = palette.mgt2 },
		Number = { fg = util.blend(palette.ylw2, palette.ylw, 0.2) },
		Operator = { fg = util.blend(palette.subtle, palette.blu2, 0.7) },
		PreCondit = { fg = palette.mgt2 },
		PreProc = { link = "PreCondit" },
		Repeat = { fg = palette.blu },
		Special = { fg = palette.blu2 },
		SpecialChar = { link = "Special" },
		SpecialComment = { fg = palette.blu2 },
		Statement = { fg = palette.blu, bold = styles.bold },
		StorageClass = { fg = palette.blu2 },
		String = { fg = util.blend(palette.grn2, palette.grn, 0.45) },
		Structure = { fg = palette.blu2 },
		Tag = { fg = palette.blu2 },
		Todo = { fg = palette.ylw, bg = palette.ylw2, blend = 20 },
		Type = { fg = palette.blu2 },
		TypeDef = { link = "Type" },
		Underlined = { fg = palette.fg, underline = true },

		healthError = { fg = palette.err },
		healthSuccess = { fg = palette.grn },
		healthWarning = { fg = palette.ylw },

		htmlArg = { fg = palette.blu2 },
		htmlBold = { bold = styles.bold },
		htmlEndTag = { fg = palette.subtle },
		htmlH1 = { link = "markdownH1" },
		htmlH2 = { link = "markdownH2" },
		htmlH3 = { link = "markdownH3" },
		htmlH4 = { link = "markdownH4" },
		htmlH5 = { link = "markdownH5" },
		htmlItalic = { italic = styles.italic },
		htmlLink = { link = "markdownUrl" },
		htmlTag = { fg = palette.subtle },
		htmlTagN = { fg = palette.fg },
		htmlTagName = { fg = palette.blu },

		markdownDelimiter = { fg = palette.subtle },
		markdownH1 = { fg = palette.red, bold = styles.bold },
		markdownH1Delimiter = { link = "markdownH1" },
		markdownH2 = { fg = palette.mgt, bold = styles.bold },
		markdownH2Delimiter = { link = "markdownH2" },
		markdownH3 = { fg = palette.cyn, bold = styles.bold },
		markdownH3Delimiter = { link = "markdownH3" },
		markdownH4 = { fg = palette.cyn2, bold = styles.bold },
		markdownH4Delimiter = { link = "markdownH4" },
		markdownH5 = { fg = palette.blu, bold = styles.bold },
		markdownH5Delimiter = { link = "markdownH5" },
		markdownH6 = { fg = palette.blu2, bold = styles.bold },
		markdownH6Delimiter = { link = "markdownH6" },
		markdownLinkText = { link = "markdownUrl" },
		markdownUrl = { fg = palette.blu2, sp = palette.blu2, underline = true },

		mkdCode = { fg = palette.blu, italic = styles.italic },
		mkdCodeDelimiter = { fg = palette.mgt },
		mkdCodeEnd = { fg = palette.blu },
		mkdCodeStart = { fg = palette.blu },
		mkdFootnotes = { fg = palette.blu },
		mkdID = { fg = palette.blu, underline = true },
		mkdInlineURL = { link = "markdownUrl" },
		mkdLink = { link = "markdownUrl" },
		mkdLinkDef = { link = "markdownUrl" },
		mkdListItemLine = { fg = palette.fg },
		mkdRule = { fg = palette.subtle },
		mkdURL = { link = "markdownUrl" },
	}
end
