return function(palette, styles)
	return {
		BlinkCmpDoc = { bg = palette.hl1 },
		BlinkCmpDocSeparator = { bg = palette.hl1 },
		BlinkCmpDocBorder = { fg = palette.hl3 },
		BlinkCmpGhostText = { fg = palette.muted },

		BlinkCmpLabel = { fg = palette.fg },
		BlinkCmpLabelDeprecated = { fg = palette.subtle, strikethrough = true },
		BlinkCmpLabelMatch = { fg = palette.blu2, bold = styles.bold },

		-- BlinkCmpMenu = { fg = palette.blu, bg = palette.bg },
		-- BlinkCmpMenuBorder = { fg = palette.subtle, bg = palette.bg },
		-- -- BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_float },
		-- -- BlinkCmpSignatureHelpBorder = { fg = c.border_highlight, bg = c.bg_float },

		BlinkCmpDefault = { fg = palette.fg },
		BlinkCmpKindText = { fg = palette.fg },
		BlinkCmpKindMethod = { fg = palette.cyn },
		BlinkCmpKindFunction = { fg = palette.cyn },
		BlinkCmpKindConstructor = { fg = palette.cyn },
		BlinkCmpKindVariable = { fg = palette.grn2 },
		BlinkCmpKindField = { fg = palette.grn2 },
		BlinkCmpKindProperty = { fg = palette.grn2 },
		BlinkCmpKindReference = { fg = palette.subtle },
		BlinkCmpKindClass = { fg = palette.blu2 },
		BlinkCmpKindInterface = { fg = palette.blu2 },
		BlinkCmpKindStruct = { fg = palette.blu2 },
		BlinkCmpKindEnum = { fg = palette.blu2 },
		BlinkCmpKindTypeParameter = { fg = palette.blu },
		BlinkCmpKindConstant = { fg = palette.red },
		BlinkCmpKindValue = { fg = palette.grn2 },
		BlinkCmpKindEnumMember = { fg = palette.grn2 },
		BlinkCmpKindKeyword = { fg = palette.ylw },
		BlinkCmpKindOperator = { fg = palette.subtle },
		BlinkCmpKindModule = { fg = palette.mgt2 },
		BlinkCmpKindFile = { fg = palette.fg },
		BlinkCmpKindFolder = { fg = palette.fg },
		-- idk
		-- BlinkCmpKindUnit = { fg = palette.grn },
		-- BlinkCmpKindSnippet = { fg = palette.blu },
		-- BlinkCmpKindColor = { fg = palette.mgt2 },
		-- BlinkCmpKindEvent = { fg = palette.cyn },
		-- BlinkCmpKindCodeium = { fg = palette.cyn2 },
		-- BlinkCmpKindCopilot = { fg = palette.cyn2 },
		-- BlinkCmpKindSupermaven = { fg = palette.cyn2 },
		-- BlinkCmpKindTabNine = { fg = palette.cyn2 },
	}
end
